title: Les Cast Codeurs Podcast

profiles:
  development:
    disqus_developer: true
  production:
    base_url: https://lescastcodeurs.com/

google_analytics:
  account: UA-3479508-5
disqus: lescastcodeurs
encoding: UTF-8
